# Travis configuration.  Build the simulator and run its tests.

language: rust
script:
  - cd sim; cargo build --release
  - cd sim; cargo run --release -- runall
  - cd sim; cargo run --release --features sig-rsa -- runall

notifications:
  slack:
    rooms:
      - secure: "L4obk4Z778hfp+oJzNM9gFRtpn5Mat6uXvdJlOaWIg3suUqeaA5j3YObFAfC2BSejgn/4UbT8XUOfD0G/ZTkBWvVungKOZeoyz/16gDsNI99RsLUjXc6Oe72nVlioqRetKB6UWQ2LGFq9fUBIwtca1A+MCdAtKJyCrdINUQl4iZ8nhllBN1ngcrQbvV5P6YOGYcF7iLPQ4rLFWLxlR9iiayBiEfP71Oq1Jeq66/Sg1leuYXVtFWPwHBLqM+AgXU8eW8kLjOl9qsC0YcxQbVISiX2vfI7luq2DLbe6OctDvipZtUv7PgzPfxGVWgnOa1qDSZ1vLAukNz70djuNrIuugQBTrOW+AVJeuPCO+NNc6L+Hp8CBqjWCMslE0lEWU9ycZOI297NPBxLB4RiiwMffko5GY3jvEPn9z1wGegKtwds2QF0GrDohMQ51bVomWmvP2gjuIvKKFH92jgjfVPQQS5fmPXSjc8TAS8sfEhYrMsKvECxeFSm2hmlMlGYjT6+zbbgKltQNQq6bcyiDugB6pQRU/BJlQNrVPAZzDRuuQ7y2cwzFhP+UZ0eAKuFUum5NtqOB/nhXHpxpmSeP6j86eIHwwuxj56Rjsqg3vZZO0eOvISIFFDRaFNPxHVo3eMfEsHuUbeFZ/3hwZZB7KkAJs5eLeF3q9CkjAj7ePPY3/0="
    on_success: always
